
package org.example.model.stamp.model;

import java.io.Serializable;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import org.example.model.stamp.Vocabulary;


/**
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_stamp_object)
public class StampObject
        extends Thing
    implements Serializable
{

    @Override
    public String toString() {
        return ((((("StampObject {"+ name)+"<")+ id)+">")+"}");
    }

}
