
package org.example.model.stamp.model;

import java.io.Serializable;
import java.util.Set;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import org.example.model.stamp.Vocabulary;


/**
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_hazard_state)
public class HazardState
    extends Situation
    implements Serializable
{

    @OWLObjectProperty(iri = Vocabulary.s_p_is_classified_by)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_hazard_state_type, min = 1, max = -1)
    })
    protected Set<Thing> is_classified_by;

    public void setIs_classified_by(Set<Thing> is_classified_by) {
        this.is_classified_by = is_classified_by;
    }

    public Set<Thing> getIs_classified_by() {
        return is_classified_by;
    }

}
