//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.25 at 01:17:54 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://documentation.bonitasoft.com/organization-xml-schema/1.1")
package model.organization;
