//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.25 at 01:28:16 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bonitasoft.org/ns/actormapping/6.0")
package cz.cvut.kbss.bpmn2stamp.converter.model.actor;
