
package org.example.model.bbo.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import org.example.model.bbo.Vocabulary;


/**
 * None: the EventDefinition which is associated through the noneEvent association will be thrown for each instance completing.
 * Any thrown Events can be caught by boundary Events on the Multi-Instance Activity.
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_NoneMultiInstanceLoopCharacteristics)
public class NoneMultiInstanceLoopCharacteristics
    extends MultiInstanceLoopCharacteristics
    implements Serializable
{


}
