
package org.example.model.bbo.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import org.example.model.bbo.Vocabulary;


/**
 * parameters that have only qualitative values
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_QualitativeParameter)
public class QualitativeParameter
    extends Parameter
    implements Serializable
{


}
