
package org.example.model.bbo.model;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import org.example.model.bbo.Vocabulary;

import java.io.Serializable;


/**
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_TimerEvent)
public class TimerEvent
    extends Event
    implements Serializable
{


}
