
package model.bbo.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import model.bbo.Vocabulary;


/**
 * /
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_ConditionExpression)
public class ConditionExpression
    extends Expression
    implements Serializable
{

    /**
     * [IRIT] specifies the SequenceFlow of the FlowNode
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_has_sequenceFlow)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_SequenceFlow, max = 1)
    })
    protected SequenceFlow has_sequenceFlow;

    public void setHas_sequenceFlow(SequenceFlow has_sequenceFlow) {
        this.has_sequenceFlow = has_sequenceFlow;
    }

    public SequenceFlow getHas_sequenceFlow() {
        return has_sequenceFlow;
    }

}
