
package model.bbo.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import model.bbo.Vocabulary;


/**
 * the Activity attached to this event should not be cancelled
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_NonInterruptingBoundaryEvent)
public class NonInterruptingBoundaryEvent
    extends BoundaryEvent
    implements Serializable
{


}
