
package model.bbo.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import model.bbo.Vocabulary;


/**
 * A Parallel Gateway is used to synchronize (combine) parallel flows and to create parallel flows.
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_ParallelGateway)
public class ParallelGateway
    extends Gateway
    implements Serializable
{


}
