
package model.bbo.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import model.bbo.Vocabulary;


/**
 * only one Activity can be performed at a time
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_SequentialAdHocSubProcess)
public class SequentialAdHocSubProcess
    extends AdHocSubProcess
    implements Serializable
{


}
