
package model.bbo.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import model.bbo.Vocabulary;


/**
 * Specific type of document containing technical information about material or software resources such as the user manual.
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_TechnicalDocument)
public class TechnicalDocument
    extends DocumentResource
    implements Serializable
{


}
