
package model.bbo.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import model.bbo.Vocabulary;


/**
 * An expression that specifies a duration, a specific date, or a cycle
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_TimeExpression)
public class TimeExpression
    extends Expression
    implements Serializable
{


}
