
package model.bbo.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import model.bbo.Vocabulary;


/**
 * /
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_TimerEventDefinition)
public class TimerEventDefinition
    extends EventDefinition
    implements Serializable
{

    /**
     * If the trigger is a Timer, then a timeCycle MAY be entered. Timer attributes are mutually exclusive and if any of the other Timer attributes is set, timeCycle MUST NOT be set (if the isExecutable attribute of the Process is set to true). The return type of the attribute timeCycle MUST conform to the ISO-8601 format for recurring time interval representations.
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_has_timeCycle)
    @ParticipationConstraints({
//        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Expression, max = 1)
    })
    protected Expression has_timeCycle;
    /**
     * If the trigger is a Timer, then a timeDate MAY be entered. Timer attributes are mutually exclusive and if any of the other Timer attributes is set, timeDate MUST NOT be set (if the isExecutable attribute of the Process is set to true). The return type of the attribute timeDate MUST conform to the ISO-8601 format for date and time representations.
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_has_timeDate)
    @ParticipationConstraints({
//        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Expression, max = 1)
    })
    protected Expression has_timeDate;
    /**
     * If the trigger is a Timer, then a timeDuration MAY be entered. Timer attributes are mutually exclusive and if any of the other Timer attributes is set, timeDuration MUST NOT be set (if the isExecutable attribute of the Process is set to true).
     * The return type of the attribute timeDuration MUST conform to the ISO-8601 format for time interval representations.
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_has_timeDuration)
    @ParticipationConstraints({
//        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Expression, max = 1)
    })
    protected Expression has_timeDuration;

    public void setHas_timeCycle(Expression has_timeCycle) {
        this.has_timeCycle = has_timeCycle;
    }

    public Expression getHas_timeCycle() {
        return has_timeCycle;
    }

    public void setHas_timeDate(Expression has_timeDate) {
        this.has_timeDate = has_timeDate;
    }

    public Expression getHas_timeDate() {
        return has_timeDate;
    }

    public void setHas_timeDuration(Expression has_timeDuration) {
        this.has_timeDuration = has_timeDuration;
    }

    public Expression getHas_timeDuration() {
        return has_timeDuration;
    }

}
