
package model.bbo.model;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;
import cz.cvut.kbss.jopa.model.annotations.Id;
import cz.cvut.kbss.jopa.model.annotations.OWLAnnotationProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import cz.cvut.kbss.jopa.model.annotations.Properties;
import cz.cvut.kbss.jopa.model.annotations.Types;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import model.bbo.Vocabulary;


/**
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_UnitOfMeasure)
public class UnitOfMeasure
        extends Thing
    implements Serializable
{
    /**
     * This relation allows to specifiy the prefix (centi, mili, etc.) of a given unit of measure.
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_has_prefix)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_UO_0000046, max = 1)
    })
    protected UO0000046 has_prefix;
    @OWLObjectProperty(iri = Vocabulary.s_p_has_unit)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_UO_0000000, min = 1, max = 1)
    })
    protected Set<Thing> has_unit;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("UnitOfMeasure {"+ name)+"<")+ id)+">")+"}");
    }

    public void setHas_prefix(UO0000046 has_prefix) {
        this.has_prefix = has_prefix;
    }

    public UO0000046 getHas_prefix() {
        return has_prefix;
    }

    public void setHas_unit(Set<Thing> has_unit) {
        this.has_unit = has_unit;
    }

    public Set<Thing> getHas_unit() {
        return has_unit;
    }

}
