
package model.bbo.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import model.bbo.Vocabulary;


/**
 * A document that describes a business process (or a work procedure)
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_WorkProcedureDocument)
public class WorkProcedureDocument
    extends TechnicalDocument
    implements Serializable
{


}
