
package model.rdf;



/**
 * This class was generated by OWL2Java 0.16.4
 * 
 */
public class Vocabulary {

    public final static String ONTOLOGY_IRI_stamp = "http://onto.fel.cvut.cz/ontologies/stamp";
    public final static String ONTOLOGY_IRI_stamp_constraints = "http://onto.fel.cvut.cz/ontologies/stamp-constraints";
    public final static String ONTOLOGY_IRI_stamp_control_structure = "http://onto.fel.cvut.cz/ontologies/stamp-control-structure";
    public final static String ONTOLOGY_IRI_stamp_generated = "http://onto.fel.cvut.cz/ontologies/stamp-generated";
    public final static String ONTOLOGY_IRI_stamp_hazard_profile = "http://onto.fel.cvut.cz/ontologies/stamp-hazard-profile";
    public final static String s_c_Thing = "http://www.w3.org/2002/07/owl#Thing";
    public final static String s_c_Occurrence = "http://onto.fel.cvut.cz/ontologies/aviation-safety/Occurrence";
    public final static String s_c_action_capability = "http://onto.fel.cvut.cz/ontologies/stamp/action-capability";
    public final static String s_c_action_control_connection = "http://onto.fel.cvut.cz/ontologies/stamp/action-control-connection";
    public final static String s_c_actuating_event = "http://onto.fel.cvut.cz/ontologies/stamp/actuating-event";
    public final static String s_c_actuator = "http://onto.fel.cvut.cz/ontologies/stamp/actuator";
    public final static String s_c_actuator_related_factors = "http://onto.fel.cvut.cz/ontologies/stamp/actuator-related-factors";
    public final static String s_c_actuator_type = "http://onto.fel.cvut.cz/ontologies/stamp/actuator-type";
    public final static String s_c_actuator_relatd_factors = "http://onto.fel.cvut.cz/ontologies/stamp/actuator_relatd_factors";
    public final static String s_c_applied_too_long = "http://onto.fel.cvut.cz/ontologies/stamp/applied-too-long";
    public final static String s_c_appropriate_control_actions_were_provided_but_not_followed = "http://onto.fel.cvut.cz/ontologies/stamp/appropriate_control_actions_were_provided_but_not_followed";
    public final static String s_c_behavioral_constraint = "http://onto.fel.cvut.cz/ontologies/stamp/behavioral-constraint";
    public final static String s_c_capability = "http://onto.fel.cvut.cz/ontologies/stamp/capability";
    public final static String s_c_causes_connection = "http://onto.fel.cvut.cz/ontologies/stamp/causes-connection";
    public final static String s_c_communication_event = "http://onto.fel.cvut.cz/ontologies/stamp/communication-event";
    public final static String s_c_communication_flaw = "http://onto.fel.cvut.cz/ontologies/stamp/communication_flaw";
    public final static String s_c_condition = "http://onto.fel.cvut.cz/ontologies/stamp/condition";
    public final static String s_c_conditional_next = "http://onto.fel.cvut.cz/ontologies/stamp/conditional-next";
    public final static String s_c_constraint = "http://onto.fel.cvut.cz/ontologies/stamp/constraint";
    public final static String s_c_control = "http://onto.fel.cvut.cz/ontologies/stamp/control";
    public final static String s_c_control_action = "http://onto.fel.cvut.cz/ontologies/stamp/control-action";
    public final static String s_c_control_capability = "http://onto.fel.cvut.cz/ontologies/stamp/control-capability";
    public final static String s_c_control_event_type = "http://onto.fel.cvut.cz/ontologies/stamp/control-event-type";
    public final static String s_c_control_loop = "http://onto.fel.cvut.cz/ontologies/stamp/control-loop";
    public final static String s_c_control_responsibility = "http://onto.fel.cvut.cz/ontologies/stamp/control-responsibility";
    public final static String s_c_control_structure = "http://onto.fel.cvut.cz/ontologies/stamp/control-structure";
    public final static String s_c_control_structure_component = "http://onto.fel.cvut.cz/ontologies/stamp/control-structure-component";
    public final static String s_c_control_structure_connection = "http://onto.fel.cvut.cz/ontologies/stamp/control-structure-connection";
    public final static String s_c_control_structure_element = "http://onto.fel.cvut.cz/ontologies/stamp/control-structure-element";
    public final static String s_c_control_action_provided_at_wrong_time = "http://onto.fel.cvut.cz/ontologies/stamp/control_action_provided_at_wrong_time";
    public final static String s_c_control_action_was_not_provided = "http://onto.fel.cvut.cz/ontologies/stamp/control_action_was_not_provided";
    public final static String s_c_controlled_process = "http://onto.fel.cvut.cz/ontologies/stamp/controlled-process";
    public final static String s_c_controller = "http://onto.fel.cvut.cz/ontologies/stamp/controller";
    public final static String s_c_controller_algorithm = "http://onto.fel.cvut.cz/ontologies/stamp/controller-algorithm";
    public final static String s_c_controller_algorithm_change = "http://onto.fel.cvut.cz/ontologies/stamp/controller-algorithm-change";
    public final static String s_c_controller_algorithm_creation = "http://onto.fel.cvut.cz/ontologies/stamp/controller-algorithm-creation";
    public final static String s_c_controller_command_action = "http://onto.fel.cvut.cz/ontologies/stamp/controller-command-action";
    public final static String s_c_controller_current_process_state = "http://onto.fel.cvut.cz/ontologies/stamp/controller-current-process-state";
    public final static String s_c_controller_current_process_state_perception = "http://onto.fel.cvut.cz/ontologies/stamp/controller-current-process-state-perception";
    public final static String s_c_controller_decision_making = "http://onto.fel.cvut.cz/ontologies/stamp/controller-decision-making";
    public final static String s_c_controller_process_model = "http://onto.fel.cvut.cz/ontologies/stamp/controller-process-model";
    public final static String s_c_controller_process_model_change = "http://onto.fel.cvut.cz/ontologies/stamp/controller-process-model-change";
    public final static String s_c_controller_process_model_creation = "http://onto.fel.cvut.cz/ontologies/stamp/controller-process-model-creation";
    public final static String s_c_controller_related_factors = "http://onto.fel.cvut.cz/ontologies/stamp/controller_related_factors";
    public final static String s_c_delayed_operations = "http://onto.fel.cvut.cz/ontologies/stamp/delayed_operations";
    public final static String s_c_factor = "http://onto.fel.cvut.cz/ontologies/stamp/factor";
    public final static String s_c_factor_type = "http://onto.fel.cvut.cz/ontologies/stamp/factor-type";
    public final static String s_c_feedback_capability = "http://onto.fel.cvut.cz/ontologies/stamp/feedback-capability";
    public final static String s_c_feedback_control_connection = "http://onto.fel.cvut.cz/ontologies/stamp/feedback-control-connection";
    public final static String s_c_general_constraint = "http://onto.fel.cvut.cz/ontologies/stamp/general-constraint";
    public final static String s_c_hazard = "http://onto.fel.cvut.cz/ontologies/stamp/hazard";
    public final static String s_c_hazard_state = "http://onto.fel.cvut.cz/ontologies/stamp/hazard-state";
    public final static String s_c_hazard_state_type = "http://onto.fel.cvut.cz/ontologies/stamp/hazard-state-type";
    public final static String s_c_hazardous_disposition = "http://onto.fel.cvut.cz/ontologies/stamp/hazardous-disposition";
    public final static String s_c_inadequate_feedback = "http://onto.fel.cvut.cz/ontologies/stamp/inadequate-feedback";
    public final static String s_c_inadequate_actuator_operation = "http://onto.fel.cvut.cz/ontologies/stamp/inadequate_actuator_operation";
    public final static String s_c_inadequate_enforcement_of_constraints = "http://onto.fel.cvut.cz/ontologies/stamp/inadequate_enforcement_of_constraints";
    public final static String s_c_inadequate_execution_of_control_actions = "http://onto.fel.cvut.cz/ontologies/stamp/inadequate_execution_of_control_actions";
    public final static String s_c_information_capability = "http://onto.fel.cvut.cz/ontologies/stamp/information-capability";
    public final static String s_c_information_control_connection = "http://onto.fel.cvut.cz/ontologies/stamp/information-control-connection";
    public final static String s_c_loss_event = "http://onto.fel.cvut.cz/ontologies/stamp/loss-event";
    public final static String s_c_loss_event_type = "http://onto.fel.cvut.cz/ontologies/stamp/loss-event-type";
    public final static String s_c_measurement = "http://onto.fel.cvut.cz/ontologies/stamp/measurement";
    public final static String s_c_must_not_occur_after = "http://onto.fel.cvut.cz/ontologies/stamp/must-not-occur-after";
    public final static String s_c_must_not_occur_before = "http://onto.fel.cvut.cz/ontologies/stamp/must-not-occur-before";
    public final static String s_c_must_occur_after = "http://onto.fel.cvut.cz/ontologies/stamp/must-occur-after";
    public final static String s_c_must_occur_before = "http://onto.fel.cvut.cz/ontologies/stamp/must-occur-before";
    public final static String s_c_nary_structure_connection = "http://onto.fel.cvut.cz/ontologies/stamp/nary-structure-connection";
    public final static String s_c_next = "http://onto.fel.cvut.cz/ontologies/stamp/next";
    public final static String s_c_not_providing = "http://onto.fel.cvut.cz/ontologies/stamp/not-providing";
    public final static String s_c_out_of_order = "http://onto.fel.cvut.cz/ontologies/stamp/out-of-order";
    public final static String s_c_passive_control = "http://onto.fel.cvut.cz/ontologies/stamp/passive-control";
    public final static String s_c_people_group = "http://onto.fel.cvut.cz/ontologies/stamp/people-group";
    public final static String s_c_person = "http://onto.fel.cvut.cz/ontologies/stamp/person";
    public final static String s_c_process = "http://onto.fel.cvut.cz/ontologies/stamp/process";
    public final static String s_c_process_changes = "http://onto.fel.cvut.cz/ontologies/stamp/process-changes";
    public final static String s_c_process_components = "http://onto.fel.cvut.cz/ontologies/stamp/process-components";
    public final static String s_c_process_connection = "http://onto.fel.cvut.cz/ontologies/stamp/process-connection";
    public final static String s_c_process_control_connection = "http://onto.fel.cvut.cz/ontologies/stamp/process-control-connection";
    public final static String s_c_process_input = "http://onto.fel.cvut.cz/ontologies/stamp/process-input";
    public final static String s_c_process_instance = "http://onto.fel.cvut.cz/ontologies/stamp/process-instance";
    public final static String s_c_process_output = "http://onto.fel.cvut.cz/ontologies/stamp/process-output";
    public final static String s_c_process_structure = "http://onto.fel.cvut.cz/ontologies/stamp/process-structure";
    public final static String s_c_process_structure_component = "http://onto.fel.cvut.cz/ontologies/stamp/process-structure-component";
    public final static String s_c_process_model_incomplete = "http://onto.fel.cvut.cz/ontologies/stamp/process_model_incomplete";
    public final static String s_c_process_model_inconsistent = "http://onto.fel.cvut.cz/ontologies/stamp/process_model_inconsistent";
    public final static String s_c_process_model_incorrect = "http://onto.fel.cvut.cz/ontologies/stamp/process_model_incorrect";
    public final static String s_c_process_model_related_factors = "http://onto.fel.cvut.cz/ontologies/stamp/process_model_related_factors";
    public final static String s_c_processing_of_feedback = "http://onto.fel.cvut.cz/ontologies/stamp/processing-of-feedback";
    public final static String s_c_providing = "http://onto.fel.cvut.cz/ontologies/stamp/providing";
    public final static String s_c_risk_enabler = "http://onto.fel.cvut.cz/ontologies/stamp/risk-enabler";
    public final static String s_c_safety_control = "http://onto.fel.cvut.cz/ontologies/stamp/safety-control";
    public final static String s_c_safety_constraint_is_not_enforced_by_the_controller = "http://onto.fel.cvut.cz/ontologies/stamp/safety_constraint_is_not_enforced_by_the_controller";
    public final static String s_c_sensing_event = "http://onto.fel.cvut.cz/ontologies/stamp/sensing-event";
    public final static String s_c_sensor = "http://onto.fel.cvut.cz/ontologies/stamp/sensor";
    public final static String s_c_sensor_related_factors = "http://onto.fel.cvut.cz/ontologies/stamp/sensor-related-factors";
    public final static String s_c_sensor_related_factors_A = "http://onto.fel.cvut.cz/ontologies/stamp/sensor_related_factors";
    public final static String s_c_stamp_event = "http://onto.fel.cvut.cz/ontologies/stamp/stamp-event";
    public final static String s_c_stamp_event_type = "http://onto.fel.cvut.cz/ontologies/stamp/stamp-event-type";
    public final static String s_c_stamp_object = "http://onto.fel.cvut.cz/ontologies/stamp/stamp-object";
    public final static String s_c_stamp_hazards = "http://onto.fel.cvut.cz/ontologies/stamp/stamp_hazards";
    public final static String s_c_state_constraint = "http://onto.fel.cvut.cz/ontologies/stamp/state-constraint";
    public final static String s_c_stopped_too_soon = "http://onto.fel.cvut.cz/ontologies/stamp/stopped-too-soon";
    public final static String s_c_structure = "http://onto.fel.cvut.cz/ontologies/stamp/structure";
    public final static String s_c_structure_component = "http://onto.fel.cvut.cz/ontologies/stamp/structure-component";
    public final static String s_c_structure_connection = "http://onto.fel.cvut.cz/ontologies/stamp/structure-connection";
    public final static String s_c_structure_element = "http://onto.fel.cvut.cz/ontologies/stamp/structure-element";
    public final static String s_c_structured_control = "http://onto.fel.cvut.cz/ontologies/stamp/structured-control";
    public final static String s_c_structured_structure_element = "http://onto.fel.cvut.cz/ontologies/stamp/structured-structure-element";
    public final static String s_c_too_early = "http://onto.fel.cvut.cz/ontologies/stamp/too-early";
    public final static String s_c_too_late = "http://onto.fel.cvut.cz/ontologies/stamp/too-late";
    public final static String s_c_type = "http://onto.fel.cvut.cz/ontologies/stamp/type";
    public final static String s_c_unsafe_action_capability = "http://onto.fel.cvut.cz/ontologies/stamp/unsafe-action-capability";
    public final static String s_c_unsafe_control_capability = "http://onto.fel.cvut.cz/ontologies/stamp/unsafe-control-capability";
    public final static String s_c_unsafe_event = "http://onto.fel.cvut.cz/ontologies/stamp/unsafe-event";
    public final static String s_c_unsafe_feedback_capability = "http://onto.fel.cvut.cz/ontologies/stamp/unsafe-feedback-capability";
    public final static String s_c_unsafe_control_action_provided = "http://onto.fel.cvut.cz/ontologies/stamp/unsafe_control_action_provided";
    public final static String s_c_unwanted_event = "http://onto.fel.cvut.cz/ontologies/stamp/unwanted-event";
    public final static String s_c_variable = "http://onto.fel.cvut.cz/ontologies/stamp/variable";
    public final static String s_c_visual_sensor_type = "http://onto.fel.cvut.cz/ontologies/stamp/visual-sensor-type";
    public final static String s_c_mental_moment = "http://onto.fel.cvut.cz/ontologies/ufo-c-ext/mental-moment";
    public final static String s_c_perception = "http://onto.fel.cvut.cz/ontologies/ufo-c-ext/perception";
    public final static String s_c_action = "http://onto.fel.cvut.cz/ontologies/ufo/action";
    public final static String s_c_agent = "http://onto.fel.cvut.cz/ontologies/ufo/agent";
    public final static String s_c_collective = "http://onto.fel.cvut.cz/ontologies/ufo/collective";
    public final static String s_c_disposition = "http://onto.fel.cvut.cz/ontologies/ufo/disposition";
    public final static String s_c_endurant = "http://onto.fel.cvut.cz/ontologies/ufo/endurant";
    public final static String s_c_endurant_type = "http://onto.fel.cvut.cz/ontologies/ufo/endurant-type";
    public final static String s_c_event = "http://onto.fel.cvut.cz/ontologies/ufo/event";
    public final static String s_c_event_type = "http://onto.fel.cvut.cz/ontologies/ufo/event-type";
    public final static String s_c_goal = "http://onto.fel.cvut.cz/ontologies/ufo/goal";
    public final static String s_c_individual = "http://onto.fel.cvut.cz/ontologies/ufo/individual";
    public final static String s_c_intention = "http://onto.fel.cvut.cz/ontologies/ufo/intention";
    public final static String s_c_perdurant = "http://onto.fel.cvut.cz/ontologies/ufo/perdurant";
    public final static String s_c_perdurant_type = "http://onto.fel.cvut.cz/ontologies/ufo/perdurant-type";
    public final static String s_c_physical_agent = "http://onto.fel.cvut.cz/ontologies/ufo/physical-agent";
    public final static String s_c_physical_object = "http://onto.fel.cvut.cz/ontologies/ufo/physical-object";
    public final static String s_c_situation = "http://onto.fel.cvut.cz/ontologies/ufo/situation";
    public final static String s_c_type_A = "http://onto.fel.cvut.cz/ontologies/ufo/type";
    public final static String s_p_causes = "http://onto.fel.cvut.cz/ontologies/aviation-safety/causes";
    public final static String s_p_contributes_to = "http://onto.fel.cvut.cz/ontologies/aviation-safety/contributes_to";
    public final static String s_p_is_factor_of = "http://onto.fel.cvut.cz/ontologies/aviation-safety/is_factor_of";
    public final static String s_p_may_be_factor_of = "http://onto.fel.cvut.cz/ontologies/aviation-safety/may_be_factor_of";
    public final static String s_p_may_cause = "http://onto.fel.cvut.cz/ontologies/aviation-safety/may_cause";
    public final static String s_p_may_contributes_to = "http://onto.fel.cvut.cz/ontologies/aviation-safety/may_contributes_to";
    public final static String s_p_may_mitigate = "http://onto.fel.cvut.cz/ontologies/aviation-safety/may_mitigate";
    public final static String s_p_may_prevent = "http://onto.fel.cvut.cz/ontologies/aviation-safety/may_prevent";
    public final static String s_p_mitigates = "http://onto.fel.cvut.cz/ontologies/aviation-safety/mitigates";
    public final static String s_p_prevents = "http://onto.fel.cvut.cz/ontologies/aviation-safety/prevents";
    public final static String s_p_caused = "http://onto.fel.cvut.cz/ontologies/stamp/caused";
    public final static String s_p_constrains = "http://onto.fel.cvut.cz/ontologies/stamp/constrains";
    public final static String s_p_controls = "http://onto.fel.cvut.cz/ontologies/stamp/controls";
    public final static String s_p_controls_for = "http://onto.fel.cvut.cz/ontologies/stamp/controls-for";
    public final static String s_p_derived_from = "http://onto.fel.cvut.cz/ontologies/stamp/derived-from";
    public final static String s_p_designed_to_enforce = "http://onto.fel.cvut.cz/ontologies/stamp/designed-to-enforce";
    public final static String s_p_enforces = "http://onto.fel.cvut.cz/ontologies/stamp/enforces";
    public final static String s_p_first_event = "http://onto.fel.cvut.cz/ontologies/stamp/first-event";
    public final static String s_p_from_structure_component = "http://onto.fel.cvut.cz/ontologies/stamp/from-structure-component";
    public final static String s_p_has_capability = "http://onto.fel.cvut.cz/ontologies/stamp/has-capability";
    public final static String s_p_has_condition = "http://onto.fel.cvut.cz/ontologies/stamp/has-condition";
    public final static String s_p_has_control_structure = "http://onto.fel.cvut.cz/ontologies/stamp/has-control-structure";
    public final static String s_p_has_control_structure_element_part = "http://onto.fel.cvut.cz/ontologies/stamp/has-control-structure-element-part";
    public final static String s_p_has_enforcement_plan = "http://onto.fel.cvut.cz/ontologies/stamp/has-enforcement-plan";
    public final static String s_p_has_goal = "http://onto.fel.cvut.cz/ontologies/stamp/has-goal";
    public final static String s_p_has_group_member = "http://onto.fel.cvut.cz/ontologies/stamp/has-group-member";
    public final static String s_p_has_manifested_state = "http://onto.fel.cvut.cz/ontologies/stamp/has-manifested-state";
    public final static String s_p_has_person_member = "http://onto.fel.cvut.cz/ontologies/stamp/has-person-member";
    public final static String s_p_has_plan = "http://onto.fel.cvut.cz/ontologies/stamp/has-plan";
    public final static String s_p_has_possible_interaction = "http://onto.fel.cvut.cz/ontologies/stamp/has-possible-interaction";
    public final static String s_p_has_responsibility = "http://onto.fel.cvut.cz/ontologies/stamp/has-responsibility";
    /**
     * the assertion A has-same-structure-as B, than A has the same structural components as B.
     * 
     */
    public final static String s_p_has_same_structure_as = "http://onto.fel.cvut.cz/ontologies/stamp/has-same-structure-as";
    public final static String s_p_in_context = "http://onto.fel.cvut.cz/ontologies/stamp/in-context";
    public final static String s_p_instance_of = "http://onto.fel.cvut.cz/ontologies/stamp/instance_of";
    public final static String s_p_interaction_after = "http://onto.fel.cvut.cz/ontologies/stamp/interaction-after";
    public final static String s_p_interaction_before = "http://onto.fel.cvut.cz/ontologies/stamp/interaction-before";
    public final static String s_p_is_group_member_of = "http://onto.fel.cvut.cz/ontologies/stamp/is-group-member-of";
    public final static String s_p_is_part_of_control_structure = "http://onto.fel.cvut.cz/ontologies/stamp/is-part-of-control-structure";
    public final static String s_p_is_person_member_of = "http://onto.fel.cvut.cz/ontologies/stamp/is-person-member-of";
    public final static String s_p_mitigates_A = "http://onto.fel.cvut.cz/ontologies/stamp/mitigates";
    public final static String s_p_next = "http://onto.fel.cvut.cz/ontologies/stamp/next";
    public final static String s_p_participates_in = "http://onto.fel.cvut.cz/ontologies/stamp/participates_in";
    public final static String s_p_process_connection_from = "http://onto.fel.cvut.cz/ontologies/stamp/process-connection-from";
    public final static String s_p_process_connection_to = "http://onto.fel.cvut.cz/ontologies/stamp/process-connection-to";
    public final static String s_p_process_has_part = "http://onto.fel.cvut.cz/ontologies/stamp/process-has-part";
    public final static String s_p_second_event = "http://onto.fel.cvut.cz/ontologies/stamp/second-event";
    public final static String s_p_source = "http://onto.fel.cvut.cz/ontologies/stamp/source";
    public final static String s_p_to_structure_component = "http://onto.fel.cvut.cz/ontologies/stamp/to-structure-component";
    public final static String s_p_violates = "http://onto.fel.cvut.cz/ontologies/stamp/violates";
    public final static String s_p_causes_A = "http://onto.fel.cvut.cz/ontologies/ufo/causes";
    public final static String s_p_has_object_part = "http://onto.fel.cvut.cz/ontologies/ufo/has-object-part";
    public final static String s_p_is_classified_by = "http://onto.fel.cvut.cz/ontologies/ufo/is-classified-by";
    public final static String s_p_is_manifested_by = "http://onto.fel.cvut.cz/ontologies/ufo/is-manifested-by";
    public final static String s_p_is_object_part_of = "http://onto.fel.cvut.cz/ontologies/ufo/is-object-part-of";
    public final static String s_p_is_participant_of = "http://onto.fel.cvut.cz/ontologies/ufo/is-participant-of";
    public final static String s_p_topObjectProperty = "http://www.w3.org/2002/07/owl#topObjectProperty";
    public final static String s_p_description = "http://purl.org/dc/terms/description";
    public final static String s_p_comment = "http://www.w3.org/2000/01/rdf-schema#comment";
    public final static String s_p_label = "http://www.w3.org/2000/01/rdf-schema#label";
    /**
     * This visual sensor is a direct observation of the operational process
     * 
     */
    public final static String s_i_direct_operation_observation = "http://onto.fel.cvut.cz/ontologies/stamp/direct-operation-observation";
    /**
     * this is strictly visual information such as signs and gestures performed by other personel or other people.
     * 
     */
    public final static String s_i_signals_from_other_people = "http://onto.fel.cvut.cz/ontologies/stamp/signals-from-other-people";

}
