//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.05 at 05:58:56 PM CEST 
//


package cz.cvut.kbss.bpmn2stamp.converter.model.actorConfig;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.bonitasoft.ns.studio.configuration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.bonitasoft.ns.studio.configuration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link Configuration.ActorMappings }
     * 
     */
    public Configuration.ActorMappings createConfigurationActorMappings() {
        return new Configuration.ActorMappings();
    }

    /**
     * Create an instance of {@link Configuration.ActorMappings.ActorMapping }
     * 
     */
    public Configuration.ActorMappings.ActorMapping createConfigurationActorMappingsActorMapping() {
        return new Configuration.ActorMappings.ActorMapping();
    }

    /**
     * Create an instance of {@link Configuration.ActorMappings.ActorMapping.Memberships }
     * 
     */
    public Configuration.ActorMappings.ActorMapping.Memberships createConfigurationActorMappingsActorMappingMemberships() {
        return new Configuration.ActorMappings.ActorMapping.Memberships();
    }

    /**
     * Create an instance of {@link Configuration.ProcessDependencies }
     * 
     */
    public Configuration.ProcessDependencies createConfigurationProcessDependencies() {
        return new Configuration.ProcessDependencies();
    }

    /**
     * Create an instance of {@link Configuration.ApplicationDependencies }
     * 
     */
    public Configuration.ApplicationDependencies createConfigurationApplicationDependencies() {
        return new Configuration.ApplicationDependencies();
    }

    /**
     * Create an instance of {@link Configuration.ActorMappings.ActorMapping.Groups }
     * 
     */
    public Configuration.ActorMappings.ActorMapping.Groups createConfigurationActorMappingsActorMappingGroups() {
        return new Configuration.ActorMappings.ActorMapping.Groups();
    }

    /**
     * Create an instance of {@link Configuration.ActorMappings.ActorMapping.Roles }
     * 
     */
    public Configuration.ActorMappings.ActorMapping.Roles createConfigurationActorMappingsActorMappingRoles() {
        return new Configuration.ActorMappings.ActorMapping.Roles();
    }

    /**
     * Create an instance of {@link Configuration.ActorMappings.ActorMapping.Users }
     * 
     */
    public Configuration.ActorMappings.ActorMapping.Users createConfigurationActorMappingsActorMappingUsers() {
        return new Configuration.ActorMappings.ActorMapping.Users();
    }

    /**
     * Create an instance of {@link Configuration.ActorMappings.ActorMapping.Memberships.Membership }
     * 
     */
    public Configuration.ActorMappings.ActorMapping.Memberships.Membership createConfigurationActorMappingsActorMappingMembershipsMembership() {
        return new Configuration.ActorMappings.ActorMapping.Memberships.Membership();
    }

}
