
package model.rdf.model;

import java.io.Serializable;
import java.util.Set;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import model.rdf.Vocabulary;


/**
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_actuator)
public class Actuator
    extends ControlStructureComponent
    implements Serializable
{

    @OWLObjectProperty(iri = Vocabulary.s_p_instance_of)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_actuator_type, min = 1, max = -1)
    })
    protected Set<Thing> instance_of;
    @OWLObjectProperty(iri = Vocabulary.s_p_is_participant_of)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_actuator_related_factors, min = 1, max = -1)
    })
    protected Set<Thing> is_participant_of;

    public void setInstance_of(Set<Thing> instance_of) {
        this.instance_of = instance_of;
    }

    public Set<Thing> getInstance_of() {
        return instance_of;
    }

    public void setIs_participant_of(Set<Thing> is_participant_of) {
        this.is_participant_of = is_participant_of;
    }

    public Set<Thing> getIs_participant_of() {
        return is_participant_of;
    }

}
