
package model.rdf.model;

import java.io.Serializable;
import java.util.Set;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import model.rdf.Vocabulary;


/**
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_control_structure_element)
public class ControlStructureElement
    extends StampObject
    implements Serializable
{

    @OWLObjectProperty(iri = Vocabulary.s_p_is_part_of_control_structure)
    protected Set<ControlStructure> is_part_of_control_structure;

    public void setIs_part_of_control_structure(Set<ControlStructure> is_part_of_control_structure) {
        this.is_part_of_control_structure = is_part_of_control_structure;
    }

    public Set<ControlStructure> getIs_part_of_control_structure() {
        return is_part_of_control_structure;
    }

}
