
package model.rdf.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import model.rdf.Vocabulary;


/**
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_inadequate_enforcement_of_constraints)
public class InadequateEnforcementOfConstraints
    extends ControllerRelatedFactors
    implements Serializable
{


}
