
package model.rdf.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import model.rdf.Vocabulary;


/**
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_structure_component)
public class StructureComponent
    extends StructureElement
    implements Serializable
{


}
