
package model.bbo.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import model.bbo.Vocabulary;


/**
 * Type of technical documentation containing the design information of a material resource.
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_EquipmentDraw)
public class EquipmentDraw
    extends TechnicalDocument
    implements Serializable
{


}
