
package model.stamp.model;

import java.io.Serializable;
import java.util.Set;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import model.stamp.Vocabulary;


/**
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_constraint)
public class Constraint
    extends GeneralConstraint
    implements Serializable
{

    @OWLObjectProperty(iri = Vocabulary.s_p_controls)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_hazard, min = 1, max = -1)
    })
    protected Set<Thing> controls;

    public void setControls(Set<Thing> controls) {
        this.controls = controls;
    }

    public Set<Thing> getControls() {
        return controls;
    }

}
