
package model.stamp.model;

import java.io.Serializable;
import java.util.Set;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import model.stamp.Vocabulary;


/**
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_factor)
public class Factor
    extends Disposition
    implements Serializable
{

    @OWLObjectProperty(iri = Vocabulary.s_p_instance_of)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_factor_type, min = 1, max = -1)
    })
    protected Set<Thing> instance_of;
    @OWLObjectProperty(iri = Vocabulary.s_p_causes_A)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_unwanted_event, min = 1, max = -1)
    })
    protected Set<Thing> causes;

    public void setInstance_of(Set<Thing> instance_of) {
        this.instance_of = instance_of;
    }

    public Set<Thing> getInstance_of() {
        return instance_of;
    }

    public void setCauses(Set<Thing> causes) {
        this.causes = causes;
    }

    public Set<Thing> getCauses() {
        return causes;
    }

}
