
package model.stamp.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import model.stamp.Vocabulary;


/**
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_stopped_too_soon__applied_too_long)
public class StoppedTooSoonAppliedTooLong
    extends UnsafeActionCapability
    implements Serializable
{


}
