//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.25 at 01:17:54 AM CET 
//


package model.organization;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bonitasoft.documentation.organization_xml_schema._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Organization_QNAME = new QName("http://documentation.bonitasoft.com/organization-xml-schema/1.1", "Organization");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bonitasoft.documentation.organization_xml_schema._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link Groups }
     * 
     */
    public Groups createGroups() {
        return new Groups();
    }

    /**
     * Create an instance of {@link Users }
     * 
     */
    public Users createUsers() {
        return new Users();
    }

    /**
     * Create an instance of {@link CustomUserInfoDefinition }
     * 
     */
    public CustomUserInfoDefinition createCustomUserInfoDefinition() {
        return new CustomUserInfoDefinition();
    }

    /**
     * Create an instance of {@link ContactData }
     * 
     */
    public ContactData createContactData() {
        return new ContactData();
    }

    /**
     * Create an instance of {@link Memberships }
     * 
     */
    public Memberships createMemberships() {
        return new Memberships();
    }

    /**
     * Create an instance of {@link Membership }
     * 
     */
    public Membership createMembership() {
        return new Membership();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link CustomUserInfoValue }
     * 
     */
    public CustomUserInfoValue createCustomUserInfoValue() {
        return new CustomUserInfoValue();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Roles }
     * 
     */
    public Roles createRoles() {
        return new Roles();
    }

    /**
     * Create an instance of {@link CustomUserInfoDefinitions }
     * 
     */
    public CustomUserInfoDefinitions createCustomUserInfoDefinitions() {
        return new CustomUserInfoDefinitions();
    }

    /**
     * Create an instance of {@link User.Password }
     * 
     */
    public User.Password createUserPassword() {
        return new User.Password();
    }

    /**
     * Create an instance of {@link User.MetaDatas }
     * 
     */
    public User.MetaDatas createUserMetaDatas() {
        return new User.MetaDatas();
    }

    /**
     * Create an instance of {@link User.CustomUserInfoValues }
     * 
     */
    public User.CustomUserInfoValues createUserCustomUserInfoValues() {
        return new User.CustomUserInfoValues();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Organization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://documentation.bonitasoft.com/organization-xml-schema/1.1", name = "Organization")
    public JAXBElement<Organization> createOrganization(Organization value) {
        return new JAXBElement<Organization>(_Organization_QNAME, Organization.class, null, value);
    }

}
