
package org.example.model.bbo.model;

import cz.cvut.kbss.jopa.model.annotations.CascadeType;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import org.example.model.bbo.Vocabulary;

import java.io.Serializable;
import java.util.Set;


/**
 * /
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_EscalationEventDefinition)
public class EscalationEventDefinition
    extends EventDefinition
    implements Serializable
{

    /**
     * If the trigger is an Escalation, then an Escalation payload MAY be provided.
     * 
     */
    @OWLObjectProperty(cascade = CascadeType.PERSIST, iri = Vocabulary.s_p_has_escalationRef)
    @ParticipationConstraints({
//        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Escalation, max = 1)
    })
    protected Set<Thing> has_escalationRef;

    public void setHas_escalationRef(Set<Thing> has_escalationRef) {
        this.has_escalationRef = has_escalationRef;
    }

    public Set<Thing> getHas_escalationRef() {
        return has_escalationRef;
    }

}
