
package org.example.model.bbo.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import org.example.model.bbo.Vocabulary;


/**
 * The StartEvent of an EventBasedSubProcess
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_EventSubProcessStartEvent)
public class EventSubProcessStartEvent
    extends SubProcessStartEvent
    implements Serializable
{


}
