
package org.example.model.bbo.model;

import cz.cvut.kbss.jopa.model.annotations.CascadeType;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import org.example.model.bbo.Vocabulary;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;


/**
 * An abstract class that binds a parameter to its value, and eventually its expected value.
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_ParameterValueBinding)
public class ParameterValueBinding
        extends Thing
    implements Serializable
{
    @OWLObjectProperty(cascade = CascadeType.PERSIST, iri = Vocabulary.s_p_has_parameter)
    @ParticipationConstraints({
//        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Parameter, min = 1, max = 1)
    })
    protected Set<Thing> has_parameter;
    @OWLObjectProperty(cascade = CascadeType.PERSIST, iri = Vocabulary.s_p_has_parameterExpectedValue)
    @ParticipationConstraints({
//        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_ParameterExpectedValue, max = 1)
    })
    protected Set<Thing> has_parameterExpectedValue;
    @OWLObjectProperty(cascade = CascadeType.PERSIST, iri = Vocabulary.s_p_has_parameterValue)
    @ParticipationConstraints({
//        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_ParameterValue, max = 1)
    })
    protected Set<Thing> has_parameterValue;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("ParameterValueBinding {"+ name)+"<")+ id)+">")+"}");
    }

    public void setHas_parameter(Set<Thing> has_parameter) {
        this.has_parameter = has_parameter;
    }

    public Set<Thing> getHas_parameter() {
        return has_parameter;
    }

    public void setHas_parameterExpectedValue(Set<Thing> has_parameterExpectedValue) {
        this.has_parameterExpectedValue = has_parameterExpectedValue;
    }

    public Set<Thing> getHas_parameterExpectedValue() {
        return has_parameterExpectedValue;
    }

    public void setHas_parameterValue(Set<Thing> has_parameterValue) {
        this.has_parameterValue = has_parameterValue;
    }

    public Set<Thing> getHas_parameterValue() {
        return has_parameterValue;
    }

}
