
package org.example.model.bbo.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import org.example.model.bbo.Vocabulary;


/**
 * all of the types of EventDefinition that are listed in the Event MUST be triggered.
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_ParallelMultipleEvent)
public class ParallelMultipleEvent
    extends MultipleEvent
    implements Serializable
{


}
