
package org.example.model.bbo.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import org.example.model.bbo.Vocabulary;


/**
 * all the Activities of the Sub-Process can be performed in parallel
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_ParallelAdHocSubProcess)
public class ParallelAdHocSubProcess
    extends AdHocSubProcess
    implements Serializable
{


}
