
package cz.cvut.kbss.bpmn2stamp.converter.model.stamp.model;

import java.io.Serializable;

import cz.cvut.kbss.bpmn2stamp.converter.model.stamp.Vocabulary;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;


/**
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_process_structure_component)
public class ProcessStructureComponent
    extends StructureComponent
    implements Serializable
{


}
