
package model.stamp.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import model.stamp.Vocabulary;


/**
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_must_not_occur_after)
public class MustNotOccurAfter
    extends BehavioralConstraint
    implements Serializable
{


}
