
package model.stamp.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import model.stamp.Vocabulary;


/**
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_appropriate_control_actions_were_provided_but_not_followed)
public class AppropriateControlActionsWereProvidedButNotFollowed
    extends ControllerRelatedFactors
    implements Serializable
{


}
