
package model.stamp.model;

import java.io.Serializable;
import java.util.Set;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import model.stamp.Vocabulary;


/**
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_control_structure_connection)
public class ControlStructureConnection
    extends StructureConnection
    implements Serializable
{

    @OWLObjectProperty(iri = Vocabulary.s_p_from_structure_component)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_control_structure_component, min = 1, max = 1)
    })
    protected Set<Thing> from_structure_component;
    @OWLObjectProperty(iri = Vocabulary.s_p_to_structure_component)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_control_structure_component, min = 1, max = 1)
    })
    protected Set<Thing> to_structure_component;

    public void setFrom_structure_component(Set<Thing> from_structure_component) {
        this.from_structure_component = from_structure_component;
    }

    public Set<Thing> getFrom_structure_component() {
        return from_structure_component;
    }

    public void setTo_structure_component(Set<Thing> to_structure_component) {
        this.to_structure_component = to_structure_component;
    }

    public Set<Thing> getTo_structure_component() {
        return to_structure_component;
    }

}
