
package cz.cvut.kbss.bpmn2stamp.converter.model.bbo.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.bpmn2stamp.converter.model.bbo.Vocabulary;


/**
 * Events that catch a trigger. All Start Events and some Intermediate Events are catching Events.
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_CatchEvent)
public class CatchEvent
    extends Event
    implements Serializable
{


}
