
package cz.cvut.kbss.bpmn2stamp.converter.model.bbo.model;

import java.io.Serializable;

import cz.cvut.kbss.bpmn2stamp.converter.model.bbo.Vocabulary;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;


/**
 * A Global Task is a reusable, atomic Task definition that can be called from within any Process by a Call Activity.
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_GlobalTask)
public class GlobalTask
    extends CallableElement
    implements Serializable
{


}
