
package cz.cvut.kbss.bpmn2stamp.converter.model.bbo.model;

import cz.cvut.kbss.bpmn2stamp.converter.model.bbo.Vocabulary;
import cz.cvut.kbss.jopa.model.annotations.CascadeType;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;


/**
 * When a CallableElement is exposed as a Service, it has to define one or more InputOutputBinding elements. An InputOutputBinding element binds one Input and one Output of the InputOutputSpecification to an Operation of a Service Interface.
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_InputOutputBinding)
public class InputOutputBinding
        extends Thing
    implements Serializable
{
    @OWLObjectProperty(cascade = CascadeType.PERSIST, iri = Vocabulary.s_p_has_callableElement)
    @ParticipationConstraints({
//        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_CallableElement, max = 1)
    })
    protected Set<Thing> has_callableElement;
    @OWLObjectProperty(cascade = CascadeType.PERSIST, iri = Vocabulary.s_p_has_inputResourceRef)
    @ParticipationConstraints({
//        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Resource, min = 1, max = 1)
    })
    protected Resource has_inputResourceRef;
    /**
     * This attribute specifies the operation that is invoked
     * 
     */
    @OWLObjectProperty(cascade = CascadeType.PERSIST, iri = Vocabulary.s_p_has_operationRef)
    @ParticipationConstraints({
//        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Operation, min = 1, max = 1)
    })
    protected Set<Thing> has_operationRef;
    @OWLObjectProperty(cascade = CascadeType.PERSIST, iri = Vocabulary.s_p_has_outputResourceRef)
    @ParticipationConstraints({
//        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Resource, min = 1, max = 1)
    })
    protected Set<Thing> has_outputResourceRef;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("InputOutputBinding {"+ name)+"<")+ id)+">")+"}");
    }

    public void setHas_callableElement(Set<Thing> has_callableElement) {
        this.has_callableElement = has_callableElement;
    }

    public Set<Thing> getHas_callableElement() {
        return has_callableElement;
    }

    public void setHas_inputResourceRef(Resource has_inputResourceRef) {
        this.has_inputResourceRef = has_inputResourceRef;
    }

    public Resource getHas_inputResourceRef() {
        return has_inputResourceRef;
    }

    public void setHas_operationRef(Set<Thing> has_operationRef) {
        this.has_operationRef = has_operationRef;
    }

    public Set<Thing> getHas_operationRef() {
        return has_operationRef;
    }

    public void setHas_outputResourceRef(Set<Thing> has_outputResourceRef) {
        this.has_outputResourceRef = has_outputResourceRef;
    }

    public Set<Thing> getHas_outputResourceRef() {
        return has_outputResourceRef;
    }

}
