
package cz.cvut.kbss.bpmn2stamp.converter.model.bbo.model;

import java.io.Serializable;

import cz.cvut.kbss.bpmn2stamp.converter.model.bbo.Vocabulary;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;


/**
 * A Message Intermediate Event can be used to either send a Message or receive a Message.
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_IntermediateThrowEvent)
public class IntermediateThrowEvent
    extends ThrowEvent
    implements Serializable
{


}
