
package cz.cvut.kbss.bpmn2stamp.converter.model.bbo.model;

import java.io.Serializable;

import cz.cvut.kbss.bpmn2stamp.converter.model.bbo.Vocabulary;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;


/**
 * A Manual Task is a Task that is expected to be performed without the aid of any business process execution engine or any application. An example of this could be a telephone technician installing a telephone at a customer location.
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_ManualTask)
public class ManualTask
    extends Task
    implements Serializable
{


}
