
package cz.cvut.kbss.bpmn2stamp.converter.model.bbo.model;

import cz.cvut.kbss.bpmn2stamp.converter.model.bbo.Vocabulary;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;

import java.io.Serializable;


/**
 * A Process that is included within another Process.
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_SubProcess)
public class SubProcess
    extends Activity
    implements Serializable
{


}
