
package cz.cvut.kbss.bpmn2stamp.converter.model.bbo.model;

import java.io.Serializable;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.bpmn2stamp.converter.model.bbo.Vocabulary;


/**
 * A User Task is a typical “workflow” Task where a human performer performs the Task with the assistance of a software application and is scheduled through a task list manager of some sort.
 * 
 * This class was generated by OWL2Java 0.16.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_UserTask)
public class UserTask
    extends Task
    implements Serializable
{


}
